webpack
aikerimm/movies pull request #1
Opened 2022-10-23 20:07 UTC by aikerimm

Configured webpack, babel, dev-server with 2 envs (dev and prod). Added eslint, lint-staged and precommit husky hook.

2022-10-24 10:24 UTC, arhigod requested changes
Пожалуйста, используй .jsx формат для реакт файлов. Ясно, что сборщик проглотит хоть .txt, но тем не менее)

2022-10-24 10:24 UTC, arhigod commented on .eslintrc.js
> +  ],
Возможно, можно ещё добавить eslint:recommended, для полноты

2022-10-24 10:24 UTC, arhigod commented on src/AllMovies.js
> +export default AllMovies
Да, не хватает каких-то еслинт правил. Так как нет ни точек с запятой, ни единообразных отступов

2022-10-24 10:24 UTC, arhigod commented on src/App.js
> +export default App
Старайся использовать стрелочные функции. И export можно делать сразу
```suggestion
export default () => (
    <div id="page">
      <Header />
      <MainContent />
      <Footer />
    </div>
  )
```

2022-10-25 04:51 UTC, aikerimm commented on .eslintrc.js
> +  ],
добавила

2022-10-25 04:53 UTC, aikerimm commented on src/AllMovies.js
> +export default AllMovies
до этого использовала готовый пресет правил, теперь сделала кастомный с ';' и отступом в 2 пробела

2022-10-25 04:53 UTC, aikerimm commented on src/App.js
> +export default App
поменяла

2022-10-25 08:14 UTC, arhigod requested changes

2022-10-25 08:14 UTC, arhigod commented on webpack.common.js
> +    bundle: path.resolve(__dirname, 'src/index.js'),
тут уже должен быть index.jsx

2022-10-25 08:14 UTC, arhigod commented on webpack.common.js
> +        test: /\.js$/,
и здесь скорее регулярка /\.jsx?$/

2022-10-25 08:14 UTC, arhigod approved these changes

2022-10-25 14:05 UTC, aikerimm commented on webpack.common.js
> +    bundle: path.resolve(__dirname, 'src/index.js'),
поменяла

2022-10-25 14:05 UTC, aikerimm commented on webpack.common.js
> +        test: /\.js$/,
поменяла

2022-10-25 14:09 UTC, aikerimm commented on src/App.js
> +export default App
здесь разделила export и объявление функции, так как eslint выдавал ошибку "missing display name"

2022-10-26 05:32 UTC, merged